<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="26521" started-at="2017-05-14T08:29:31Z" finished-at="2017-05-14T08:29:57Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="26521" started-at="2017-05-14T08:29:31Z" finished-at="2017-05-14T08:29:57Z">
      <class name="com.ninjacart.scripts.DirectsScripts">
        <test-method status="PASS" signature="start()[pri:0, instance:com.ninjacart.scripts.DirectsScripts@6bf256fa]" name="start" is-config="true" duration-ms="360" started-at="2017-05-14T13:59:30Z" finished-at="2017-05-14T13:59:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="FAIL" signature="createSaleOrderAndRevaluateSlabPriceAndValidate()[pri:0, instance:com.ninjacart.scripts.DirectsScripts@6bf256fa]" name="createSaleOrderAndRevaluateSlabPriceAndValidate" duration-ms="25395" started-at="2017-05-14T13:59:31Z" finished-at="2017-05-14T13:59:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at com.ninjacart.genericLibrary.GenericKeywords.loadURL(GenericKeywords.java:618)
	at com.ninjacart.businessLibrary.BusinessKeywords.loginToBiFrost(BusinessKeywords.java:70)
	at com.ninjacart.businessLibrary.BusinessKeywords.createPOForDirectApp(BusinessKeywords.java:251)
	at com.ninjacart.scripts.DirectsScripts.createSaleOrderAndRevaluateSlabPriceAndValidate(DirectsScripts.java:580)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSaleOrderAndRevaluateSlabPriceAndValidate -->
        <test-method status="FAIL" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.ninjacart.scripts.DirectsScripts@6bf256fa]" name="tearDown" is-config="true" duration-ms="0" started-at="2017-05-14T13:59:56Z" finished-at="2017-05-14T13:59:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createSaleOrderAndRevaluateSlabPriceAndValidate status=FAILURE method=DirectsScripts.createSaleOrderAndRevaluateSlabPriceAndValidate()[pri:0, instance:com.ninjacart.scripts.DirectsScripts@6bf256fa] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at com.ninjacart.genericLibrary.GenericKeywords.captureScreenshot(GenericKeywords.java:330)
	at com.ninjacart.scripts.DirectsScripts.tearDown(DirectsScripts.java:997)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:786)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="SKIP" signature="last()[pri:0, instance:com.ninjacart.scripts.DirectsScripts@6bf256fa]" name="last" is-config="true" duration-ms="0" started-at="2017-05-14T13:59:57Z" finished-at="2017-05-14T13:59:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- last -->
      </class> <!-- com.ninjacart.scripts.DirectsScripts -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
